# Generated by Django 6.0.5 on 2026-05-20 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='트랙 이름')),
            ],
        ),
        migrations.AddField(
            model_name='lion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lion',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lions_app.track', verbose_name='트랙'),
        ),
    ]
