# Generated by Django 6.0.5 on 2026-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lions_app', '0002_track_lion_created_at_alter_lion_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lion',
            name='track',
            field=models.CharField(choices=[('Django', 'Django'), ('SpringBoot', 'SpringBoot'), ('Frontend', 'Frontend')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
